spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/musicloud?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: stili
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      defer-datasource-initialization: true
  servlet.multipart.max-file-size: 20MB
  servlet.multipart.max-request-size: 20MB
  mvc:
    hiddenmethod:
      filter:
        enabled: true